FROM python:3.5.9-alpine3.10
MAINTAINER yangx.p.li@intel.com
ENV http_proxy http://10.239.4.160:913
ENV https_proxy http://10.239.4.160:913
RUN apk add python3-dev libressl-dev libxml2-dev libffi-dev && apk add --update alpine-sdk
RUN pip install openssh-clients

