FROM ubuntu:16.04
MAINTAINER yangx.p.li@intel.com
ENV http_proxy http://10.239.4.160:913
ENV https_proxy http://10.239.4.160:913
RUN apt-get update && apt-get install -yq dnsutils
#RUN apt-get install -y python3-pip
#RUN pip3 install django==2.0.0
#RUN pip3 install requests==2.22.0 
#COPY NodeInfo /root/NodeInfo
#WORKDIR /root/NodeInfo
#RUN chmod a+x /root/NodeInfo/start.sh
#EXPOSE 8002
#CMD ["./start.sh"]

